---
- name: Clean APT cache on Debian-based systems
  hosts: servers
  become: yes
  tasks:
    - name: Clean APT cache
      apt:
        update_cache: no
        autoclean: yes
        autoremove: yes
