---
- name: Update Linux Servers
  hosts: updateservers
  become: yes
  tasks:
    - name: Update all packages (Debian/Ubuntu)
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Update all packages (RedHat/CentOS)
      ansible.builtin.yum:
        update_cache: yes
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Check if reboot is required (Debian/Ubuntu)
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file
      when: ansible_os_family == "Debian"

    - name: Check if reboot is required (RedHat/CentOS)
      ansible.builtin.command: needs-restarting -r
      register: needs_restarting_result
      changed_when: false # This command doesn't change system state
      when: ansible_os_family == "RedHat"

    - name: Reboot server if necessary (Debian/Ubuntu)
      ansible.builtin.reboot:
      when: ansible_os_family == "Debian" and reboot_required_file.stat.exists

    - name: Reboot server if necessary (RedHat/CentOS)
      ansible.builtin.reboot:
      when: ansible_os_family == "RedHat" and needs_restarting_result.rc == 1
