- name: Rolling update of app container
  hosts: my_app_servers
  become: true
  serial: 1
  tasks:
    - name: Pull latest image
      docker_image:
        name: linuxserver/syncthing:latest
        source: pull
      register: result

    - name: Recreate app container only if image changed
      docker_container:
        name: syncthing
        image: linuxserver/syncthing:latest
        state: started
        recreate: yes
      when: result.changed
